use std::error::Error;

pub fn solve() -> Result<(), Box<dyn Error>> {
    println!("Not yet solved");
    Ok(())
}
